### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by matthewp** [canjs/can-element#1]
I threw something together real quick that does the absolute basics:

1. Takes a ViewModel and puts its properties on the element.
2. Renders to shadow dom with a template.

More things we need:

* [ ] - Maybe the ability to render to the element's child instead of shadow DOM since shadow DOM doesn't let any global styles in.
* [ ] - Make a real scope, figure out what to do there.
* [x] - Get the passed in props/attributes and pass those into the ViewModel when it is created
* [ ] - Bind attributes to properties

and probably a lot more.

@pYr0x @justinbmeyer 

https://github.com/canjs/can-custom-elements/blob/master/test/test.js#L11

**Comment by justinbmeyer** [comment]
Awesome! I'm wondering if there should be a separate view model. I've been thinking we might use can-define directly on the element.

**Comment by matthewp** [comment]
I made it use can-define directly which comes out like this:

```js
class MyApp extends CanElement {
	static get view() {
		return view;
	}
}

define(MyApp.prototype, {
	name: {
		value: "world"
	}
});
```

Since classes can be mixed in through function calls, it would be nice if can-define had a signature like this:

```js
var defined = define.mixin({
	name: {
		value: "world"
	}
});

class MyApp extends defined(CanElement) {
	static get view() {
		return view;
	}
}
```

**Comment by matthewp** [comment]
One issue to keep in mind is that standard elements don't have side-effects just by creating them and we should preserve this behavior in our own. Let's say we have a todo-list element that makes requests to fetch todos.  This:

```js
var todoList = document.createElement("todo-list");
```

Should **not** start making requests.  This *should*:

```js
document.body.appendChild(todoList);
```

You can trigger side-effects by setting setters though. Think about the `img` element which will start fetching as soon as you set the `src` property.

**Comment by matthewp** [comment]
So I got scoping to work which means that bindings work in stache:

```js
<some-child {foo}="bar"></some-child>
```

This will get `bar` from the parent scope and pass it in. 

To make this template-language neutral this is how it currently works: https://github.com/canjs/can-custom-elements/blob/master/test/test.js#L10

This is ugly. We don't have a tagData kind of thing like with can-component so we can't pass a setupBindings function that way.  I think the setupBindings function should be on the renderer function so that if you do something like this:

```js
var stache = require("can-stache");
require("can-stache-bindings");

var view = stache("{{foo}}");

view.setupBindings(el);
```

Open to a better way to have this function be available generically though.  cc @justinbmeyer

**Comment by matthewp** [comment]
I want to make it so that you can bind attributes to properties. This should probably happen automatically for attributes -> properties but for the other direction that's not so clear. I think I might make a custom can-define behavior that works like so:

```js
define(SomeElement.prototype, {
  foo: {
    value: "bar",
    attribute: true
  }
});
```

This means that if someone does this:

```js
var el = document.querySelector("some-element");
el.foo = "something else";
```

The attribute would be updated to reflect that change.  Going to put it in can-custom-elements/attribute for now, might make it part of the base stuff later.

**Comment by matthewp** [comment]
Closing this in favor of individual issues:

https://github.com/canjs/can-custom-elements/issues/3
https://github.com/canjs/can-custom-elements/issues/2

**Comment by justinbmeyer** [comment]
Value and value are only run when read, so they should work pretty well.
