### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by pYr0x** [canjs/can-element#12]
many people have learned canjs's `can-component` syntax and workflow.
an example from canjs docs
```
var HelloWorldVM = DefineMap.extend({
    visible: {value: false},
    message: {value: "Hello There!"}
});

Component.extend({
  tag: "hello-world",
  view: stache("{{#if visible}}{{message}}{{else}}Click me{{/if}}"),
  ViewModel: HelloWorldVM,
  events: {
    click: function(){
        this.viewModel.visible = !this.viewModel.visible;
    }
  }
});
```

as i see in the tests, writing a `can-custom-element` is completely different. @matthewp uses ES6 syntax which completly OK. but i would like to have a second syntax that is very similar to `can-component`
```
Element.extend({
  tag: "hello-world",
  view: stache("{{#if visible}}{{message}}{{else}}Click me{{/if}}"),
  ViewModel: HelloWorldVM
  }
});
```

**Comment by matthewp** [comment]
We could probably provide this. However I think over time you'll prefer ES6 classes to can-construct as you'll be using them in any other non-CanJS libraries you use.

One nice part of using the class syntax is that the element you create is a constructor which means you can call `new` on it:

```js
var HelloWorld = class extends Element {
   ...
}

customElements.define("hello-world", HelloWorld);

// You can use it like this
var helloWorld = document.createElement("hello-world");

// Or like this:
var helloWorld = new HelloWorld();
```

But I'm not opposed to a more can-3 like syntax as a separate import, maybe under `var Component = require("can-custom-elements/component");`

**Comment by matthewp** [comment]
We're looking at a new API that is more like https://github.com/canjs/can-element/issues/37. So not like the current API but also not really like can-component.
