### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by pYr0x** [canjs/can-element#20]
I saw can-custom-element uses new JavaScript features like the Reflect API or the Shadow DOM.
To make can-custom-element compatible with IE we need some polyfills.
For the Reflect API we need babel's polyfill http://babeljs.io/learn-es2015/#ecmascript-2015-features-reflect-api
To use the Shadow DOM we need the Webcomponents polyfill https://www.webcomponents.org/polyfills

Today can-custom-element will only work on chrome and Safari. 
Is there a need to support other browsers or do we limit can-custom-element to these few working  browsers?

**Comment by matthewp** [comment]
I created #10 to document this.  With polyfills it will go back to IE11 for shadow dom or IE8 if you just use custom elements.  can-custom-elements is only 4 days old so compat hasn't been a priority yet 😜

**Comment by matthewp** [comment]
Closing since #10 is the same issue.
