### ISSUE TITLE
Find a better way to setup VM bindings

### ISSUE THREAD

**Issue by matthewp** [canjs/can-element#3]
So I got scoping to work which means that bindings work in stache:

```<some-child {foo}="bar"></some-child>```
This will get bar from the parent scope and pass it in.

To make this template-language neutral this is how it currently works: https://github.com/canjs/can-custom-elements/blob/master/test/test.js#L10

This is ugly. We don't have a tagData kind of thing like with can-component so we can't pass a setupBindings function that way. I think the setupBindings function should be on the renderer function so that if you do something like this:
```js
var stache = require("can-stache");
require("can-stache-bindings");

var view = stache("{{foo}}");

view.setupBindings(el);
```
Open to a better way to have this function be available generically though. cc @justinbmeyer

**Comment by matthewp** [comment]
#11 made it so that we get tagData when rendered within a template.

We need a way for can-stache-bindings to set itself on that tagData object.

**Comment by matthewp** [comment]
@justinbmeyer is it reasonable to have a `types.setupBindings` that can-stache-bindings (and any other bindings library) would set itself on?  This way we don't have to depend on can-stache-bindings like can-component does.

The signature would be like this: https://github.com/canjs/can-component/blob/master/can-component.js#L149

**Comment by justinbmeyer** [comment]
It's an improvement, but I think the template should provide the bindings. I'm not able to follow along with everything you're doing, so let's catch up on Monday (might have time to look at it tonight)

**Comment by matthewp** [comment]
Sure, no worries, we can discuss next week any time.

**Comment by matthewp** [comment]
Actually, since the VM is the element, shouldn't need to setup VM bindings at all, the normal bindings should work on their own. Will investigate this more.

**Comment by justinbmeyer** [comment]
Currently, we setup bindings at the same time the VM is created. I forgot all the reasons why. 

On reason is to prevent events from being dispatched while no one could be listening.

**Comment by matthewp** [comment]
In this case the element is the VM. We can't set up bindings at construction because we don't have the tagData at that time. Perhaps there could be a better way to pass the tagData to the element's constructor. For now I've fixed it so that normal element property bindings works in #13.
